### ISSUE TITLE
advertisementData from iOS and Android are different

### ISSUE THREAD

**Issue by lchinke** [pauldemarco/flutter_blue#101]
Hi,

I am actually trying to use the advertismentData retrieved by the scan method but in iOS the information is very different than in iOS. 

What could I do to retrieve the specific information I am looking for?

Thank you.

**Comment by lchinke** [comment]
Maybe this is due to "iOS does not allow you to access the RAW advertisement data."?

**Comment by lchinke** [comment]
Well. Sorry for my ignorance and lack of searching before creating this Issue. 

CoreLocation / CBCentralManager doesn't retrieve this kind of data.

**Comment by pauldemarco** [comment]
Closed in favor of #102
