### ISSUE TITLE
heart rate measurement characteristics not read

### ISSUE THREAD

**Issue by giroskii** [pauldemarco/flutter_blue#1038]
I used heart rate data for mi band4, 5
"00002a37-0000-1000-8000-00805f9b34fb" this uuid can be read on iOS, but not on Android.

Android was this characteristics.properties.read = false 
but iOS return true
and also bonded using the mi band official app.
what should i do to solve this problem?

this is my code :

    for (blep.BluetoothCharacteristic c in _service!.characteristics) {
      String uuid = "0x${c.uuid.toString().toLowerCase().substring(4, 8)}";
      if (c.properties.read) {
        if (c.isNotifying) {
          await c.setNotifyValue(true);
        }
        c.read();
        if (uuid == "0x2a37") {
          debugPrint(
              ":::::::::: Heart Rate Measurement => ${c.lastValue[1]} ::::::::::");
        } else if (uuid == "0x2a39") {
          debugPrint(
              ":::::::::: Heart Rate Control Point => ${c.lastValue[1]} ::::::::::");
        }
      }
    }

**Comment by brutalzinn** [comment]
how did you solve this problem?

**Comment by giroskii** [comment]
@brutalzinn 
i solved this problem used try ~ catch
If a catch error appears, it is already connected, and if there is no error, it is judged as disconnect.

**Comment by giroskii** [comment]
> how did you solve this problem?

@brutalzinn
i solved this problem used try ~ catch
If a catch error appears, it is already connected, and if there is no error, it is judged as disconnect.
