### ISSUE TITLE
how to set value in ( service data) in my bluetooth device

### ISSUE THREAD

**Issue by yabakhar** [pauldemarco/flutter_blue#1049]
how to set value in ( service data OR service data) in my bluetooth device
![whatsapp](https://user-images.githubusercontent.com/38636953/161791905-f06c3928-824f-4c23-8385-98e790181e05.jpg)

**Comment by yabakhar** [comment]
how to set value in ( service data OR service data) in my bluetooth device

**Comment by AguSampietro** [comment]
This package hasn't been maintaining lately. I suggest you to migrate to flutter_blue_plus.
