### ISSUE TITLE
servicesDiscoveredSink is null

### ISSUE THREAD

**Issue by IvanDreamer** [pauldemarco/flutter_blue#107]
Hi! I have an issue while I'm trying to connect to a service. When I scan a connected device for services I get following: 

`D/FlutterBluePlugin(25041): onServicesDiscovered: 10 sink:null`

As I understood it found 10 services, but for some reason `servicesDiscoveredSink` is null. 

Does someone know why?

**Comment by Bakhoj** [comment]
I don't know why it does that, put I've posted my short term solution on Issue #30 which seems to address the same problem as this.

**Comment by IvanDreamer** [comment]
@Bakhoj thank you for the reference. I also did the second scan manually till it will find.

**Comment by sophisticode** [comment]
Pull request #132 should fix this issue.
