### ISSUE TITLE
Scan results are empty in Android 11 and above

### ISSUE THREAD

**Issue by kausikMR** [pauldemarco/flutter_blue#1078]

**Comment by yoosinpaddy** [comment]
Android 10 onwards require background location permission access and location services enabled in order to get device list.
I have edited the package and published it [here](https://github.com/yoosinpaddy/flutter_blue-master-android-10-11.git)
I hope it helps

**Comment by boskokg** [comment]
please go to flutter_blue_plus where we continued plugin development

**Comment by kausikMR** [comment]
I switched to the flutter_blue_plus package, working fine now thanks!
