### ISSUE TITLE
Is this a active project? 

### ISSUE THREAD

**Issue by lgLindstrom** [pauldemarco/flutter_blue#1116]
Still no support för Linux, Web and Windows so,,, is the project abounded?

**Comment by nairboon** [comment]
No, this project is no longer active. 
Consider using [flutter_blue_plus](https://github.com/boskokg/flutter_blue_plus) instead.

**Comment by lgLindstrom** [comment]
Thanks,
Any plans to make it aviable for Linux and Windows?


Den tis 27 dec. 2022 17:26Remo H ***@***.***> skrev:

**Comment by Pierre-Monier** [comment]
In that case, can someone mark the plugin as discontinued ?

**Comment by pauldemarco** [comment]
This repo is in a stable state and is being used in some products. I plan on adding more features and platform support in the future. Please feel free to follow other more active forks.
