### ISSUE TITLE
Bluetooth Keyboard devices are not showing up in Scan APi

### ISSUE THREAD

**Issue by pravinarr** [pauldemarco/flutter_blue#115]
Hello,

I am trying to scan and connect to a bluetooth barcode scanner which is configured to run as bluetooth keyboard by the manufacturer.  The device is showing up in the native Settings->Bluetooth page but when I try to scan for the devices through Flutter_Blue Api, it is showing up all the devices except keyboard items.

Please help me to identify the problem so that I can fix it.

thank you in advance.

**Comment by pauldemarco** [comment]
The device might not be Bluetooth Low Energy, which is what this library supports.

There are no plans at the moment to support Bluetooth Classic.

Perhaps if you share more about the keyboard (model number), I could further verify.

**Comment by pravinarr** [comment]
I was using a Bluetooth classic device ( http://a.co/d/5RZMoSX ). @pauldemarco thank you for letting me know.
