### ISSUE TITLE
What is the method to determine no scan device found to empty the list?

### ISSUE THREAD

**Issue by alextran1502** [pauldemarco/flutter_blue#121]
Hello, I am building a BLE scan app and I am getting stuck on how to identify when no scan data is return in order to "pop" the device from a list.

What are the method are you guys using?

Thanks,

**Comment by Fleximex** [comment]
Not sure if I understand.
The FlutterBlue.scan method will return a stream of results which you can add to a list. You can check for that list to be empty. 
I'm relatively new to Bluetooth and Flutter, but I noticed Flutter Blue to find a lot of "devices" with no name (which I don't know what they are). If I add devices (scan results) to the list I check for the device if it has a name. So:
```
for (ScanResult sr in tempList) {
   if (sr.advertisementData.localName.length > 0) {
      correctedList.add(sr);
   }
}
```
