### ISSUE TITLE
Unable to write a characteristics in IPhone

### ISSUE THREAD

**Issue by aravindara** [pauldemarco/flutter_blue#131]
Same app which is running perfectly in Android is failed to write characteristics in IOS

**Comment by pauldemarco** [comment]
@aravindara I would need some more information if I'm to try and solve the issue.

What does the code look like?

What is the structure of the Bluetooth Characteristic / does it have descriptors?

**Comment by aduarte88** [comment]
I have the same problem
in android works but in ios not
I have already been able to write in iOS of type "withoutResponse" but when it is "withResponse" it gives this error

**Comment by tgeukens** [comment]
@aduarte88  I had a similar issue running the basic example in the project.  Double check whether the characteristic actually has the 'write' flag set in the characteristic declaration.  On iOS you'll indeed get an error trying to write with response on a characteristic that only supports write without response.  You can double check the characteristic's declaration by inspecting the characteristic.properties.writeWithoutResponse and characteristic.properties.write flags.  The example does not differentiate between these 2 types of writes (yet).  I'm pretty new to dart/flutter but this should fix the example I believe:

```
_writeCharacteristic(BluetoothCharacteristic c) async {
    CharacteristicWriteType writeType = c.properties.writeWithoutResponse
        ? CharacteristicWriteType.withoutResponse
        : CharacteristicWriteType.withResponse;
    await device.writeCharacteristic(c, [0x12, 0x34], type: writeType);
    setState(() {});
  }```

**Comment by 100cm** [comment]
i have fixed this by listen the notification.

**Comment by pauldemarco** [comment]
This issue seems to be resolved. Closing for now.

**Comment by micromotores** [comment]
i have a this problem ,help me please
![Captura de Pantalla 2021-02-22 a la(s) 4 08 36 p  m](https://user-images.githubusercontent.com/79323549/108770585-7959c500-7528-11eb-9c33-1f65b7c66934.png)
