### ISSUE TITLE
I can't recevice [ble to phone] data by use 'setNotifyValue'

### ISSUE THREAD

**Issue by VayneKaso** [pauldemarco/flutter_blue#139]
`
curConnectDevice.setNotifyValue(availableCharacteristic, true);

final sub = curConnectDevice.onValueChanged(availableCharacteristic).listen((d) {
  print('$tag onValueChanged $d');
});

valueChangedSubscriptions[availableCharacteristic.uuid] = sub;

`

I use it follow your example in github
I use availableCharacteristic to 'writeCharacteristic'. but i don't recevice ble's data when write success.

**Comment by VayneKaso** [comment]
please give me a little help.this is a so big trouble for my work. connect ble is the most basic and important for my developertask

**Comment by VayneKaso** [comment]
who can help me？ how to receive data for ble？Today I searched entire network but without a template code .

**Comment by pauldemarco** [comment]
@VayneKaso 
This may be because the device you are connecting to is not setup properly to support notifications.

Can you share a little more information on the device?

**Comment by david-gam** [comment]
I'm trying to connect a glucometer with flutter but I could not write or receive the stored readings or the new glucose readings, can anyone have an example or know how I can solve this?
glucose service: 00001808-0000-1000-8000-00805f9b34fb
glucose measurement: 00002a18-0000-1000-8000-00805f9b34fb
RECORDS CHARACTERISTIC: 00002a52-0000-1000-8000-00805f9b34fb
CLIENT CHARACTERISTIC CONFIG: 00002902-0000-1000-8000-00805f9b34fb

**Comment by pauldemarco** [comment]
This question is better suited for a QA site, like [stackoverflow](https://stackoverflow.com), where it can be indexed for others to learn from as well.

Please provide code snippets and any other information that might lead you to believe it is a bug with the plugin, and we can re-open the issue.
