### ISSUE TITLE
Android and iOS differences for BluetoothDevice.id

### ISSUE THREAD

**Issue by shinayser** [pauldemarco/flutter_blue#148]
First, thanks for this awesome plugin!

When getting the "id" of the device (BluetoothDevice.id.id), Android returns the MAC Address of the bluetooth antenna in the format "00:00:00:00:00:00" but iOS returns "00000000-0000-0000-0000-000000000000".

It causes problems when trying to show the device mac address on the interface.

There is any workaround on it ?

**Comment by pauldemarco** [comment]
Closing this for now, please re-open if needed.
