### ISSUE TITLE
Build does not work with latest flutter

### ISSUE THREAD

**Issue by ride4sun** [pauldemarco/flutter_blue#155]
If I use the latest flutter with the current flutter_blue version I get that error after just adding the package to any project and creating the FlutterBlue.instance.

ERROR in build:
18:19:05.343 74 info flutter.tools            The Android Gradle plugin supports only Protobuf Gradle plugin version 0.8.6 and higher. Project 'flutter_blue' is using version 0.8.3.

This is the build gradle file in flutter_blue I changed to 0.8.6:
```
group 'com.pauldemarco.flutterblue'
version '1.0-SNAPSHOT'

buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.3'
```
I still got a compile error pointing to the build.gradle has to be minSdkVersion: 19 I changed from 16
Than it worked!

```
  defaultConfig {
         // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
         applicationId "com.example.bluetoothtest"
         minSdkVersion 19
         targetSdkVersion 27
         versionCode flutterVersionCode.toInteger()
         versionName flutterVersionName
         testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
```

C:\Projects\bluetooth_test>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.1.5-pre.5, on Microsoft Windows [Version 10.0.17134.472], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.2)
[√] IntelliJ IDEA Community Edition (version 2017.3)
[√] VS Code, 32-bit edition (version 1.28.2)
[√] Connected device (2 available)

**Comment by pauldemarco** [comment]
Fixed in 2cf8cecb2f0f2bd80dd8562fa9ed8de0102954ef

**Comment by ride4sun** [comment]
thx

**Comment by mathieujobin** [comment]
I am getting this error.
`D8: Program type already present: android.support.v4.app.INotificationSideChannel`

is this related?
