### ISSUE TITLE
Can't connect with Raspberry Pi 3b+

### ISSUE THREAD

**Issue by jemutorres** [pauldemarco/flutter_blue#171]
I'm trying to connect with Raspberry Pi 3b+.

The Raspberry have Raspbian Stretch Lite with Bluetooth 4.2. It's visible and If I go to Settings > Bluetooth on my phone, I found the raspberry.

I downloaded the example. I've done a search from the same phone and I can't find the Raspberry.

**Comment by jonasgaiswinkler** [comment]
I'm having the same issue with my Raspberry Pi Zero W

**Comment by jonasgaiswinkler** [comment]
I found these instructions which work fine for me: [Bluetooth with Raspberry Pi and bleno](https://www.skyrise.tech/blog/tech/bluetooth-raspberry-pi-bleno-part-1-ibeacon/)

**Comment by stuartsoft** [comment]
Ditto here to. Can we get some updates on this ticket?

**Comment by stuartsoft** [comment]
@pauldemarco  If you happen to have a moment to check on this I would really appreciate it. The scanning process works fine, I'm able to see the device I want and obtain a `BluetoothDevice` object. The problem occurs when I try to actually connect to said device. Below is the log info I see when calling `flutterBlue.connect().listen()` from my Flutter app

```
D/BluetoothManager(26256): getConnectedDevices
D/BluetoothGatt(26256): connect() - device: CENSORED_MAC_ADDRESS, auto: true
D/BluetoothGatt(26256): registerApp()
D/BluetoothGatt(26256): registerApp() - UUID=CENSORED_UUID
D/BluetoothGatt(26256): onClientRegistered() - status=0 clientIf=10
D/BluetoothGatt(26256): close()
D/BluetoothGatt(26256): unregisterApp() - mClientIf=10
```

and for reference, here is the snippet I'm using to initiate a connection:
```dart
_fbconnection = this
              .widget
              .flutterBlue
              .connect(this.widget.device,
                  autoConnect: true, timeout: Duration(seconds: 60))
              .listen((state) {
            setState(() {
              debugPrint("new state: " + state.toString());
              this._deviceState = state;
            });
          });
```

I've been able to confirm that I can connect my Pixel 3 XL to my Pi 3B using the following two sample projects from Google. So, that at least proves that my hardware is good.
https://github.com/androidthings/sample-bluetooth-le-gattserver
https://github.com/googlesamples/android-BluetoothLeGatt

**Comment by stuartsoft** [comment]
I'm getting the impression that this library just straight up doesn't work on Android. I'm using the example scanner provided in THIS repository and it's unable to connect to my BLE Raspberry Pi. Meanwhile, Google's own BLE example works fine and connects to the same Pi running the same code. `¯\_(ツ)_/¯`

**Comment by stuartsoft** [comment]
Never mind. We're all good. Turns out the connection works when you set `autoconnect: false` when attempting to connect. @pauldemarco  I guess it's just an issue when trying to connect with autoconnect on, as pointed out by this person: https://github.com/pauldemarco/flutter_blue/issues/106#issuecomment-448141259
