### ISSUE TITLE
what's the format of writeCharacteristic'

### ISSUE THREAD

**Issue by 100cm** [pauldemarco/flutter_blue#177]
![image](https://user-images.githubusercontent.com/12691638/51517902-43cce400-1e57-11e9-887b-6fe61c16b7ce.png)
```
    Future a = await device.writeCharacteristic(c, [0x0566A0330A],
        type: CharacteristicWriteType.withResponse);
    print(a.toString());
    setState(() {});
```

i want to send this bytes ,but the param type is List<int>

i send the string in  objective-c.

**Comment by lemonbuzz** [comment]
I think you want something like this in the array
[0x05,0x66,0xA0,0x33,0x0A]

**Comment by 100cm** [comment]
@lemonbuzz thanks a lot ! dude! but it must in hexadecimal?
my workmate write a java function for me 

```
    public static byte[] hex2byte(String hex) {
        String digital = "0123456789ABCDEF";
        char[] hex2char = hex.toCharArray();
        byte[] bytes = new byte[hex.length() / 2];
        int temp;
        for (int i = 0; i < bytes.length; i++) {
            temp = digital.indexOf(hex2char[2 * i]) * 16;
            temp += digital.indexOf(hex2char[2 * i + 1]);
            bytes[i] = (byte) (temp & 0xff);
        }
        return bytes;
    }
```

but the result is `[5, 102, -96, 51, 10]`

and  `[0x05,0x66,0xA0,0x33,0x0A]` equals   `[5, 102, 160, 51, 10]`

i don't why the third number is different.

**Comment by lemonbuzz** [comment]
Take a look at this
https://api.dartlang.org/stable/2.1.0/dart-convert/Encoding-class.html

encode method returns the buffer you can pass to writeCharacteristics

Pretty useful with ascii, i use it to send commands to my esp32 app :)

**Comment by d3rf** [comment]
My ESP is expecting for String, so how create a Method to write as String ?

**Comment by jpcEngineer** [comment]
That list of int's are Hex,
![write](https://user-images.githubusercontent.com/47160520/52236720-34a15980-288d-11e9-9416-cd765b84c3e6.PNG)

**Comment by 100cm** [comment]
finally i solved this problem. close the issue.

**Comment by kamilk91** [comment]
@100cm  how? i have the same problem now.
