### ISSUE TITLE
Rename startScan to scan

### ISSUE THREAD

**Issue by pauldemarco** [pauldemarco/flutter_blue#18]
Now that scanning stops once the subscription to startScan is canceled, we can consider renaming startScan to simply scan.
Original suggestion by @brianegan in PR #17 .

I will be considering this breaking change for a bit, but I'm leaning towards implementing.  If you have some thoughts please share.

**Comment by brianegan** [comment]
Now that I've seen `connect` as well, I'd say it makes even more sense :)

`scan` / `connect` seem like a good pair.
