### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by pauldemarco** [pauldemarco/flutter_blue#20]
An Objective-C implementation is still needed on iOS side.

**Comment by JohannesTr** [comment]
Hi, is the iOS implementation in development at the moment?

**Comment by pauldemarco** [comment]
Hi Johannes,

It is not, feel free to send PRs :)

On Dec 11, 2017 7:31 PM, "JohannesTr" <notifications@github.com> wrote:

Hi, is the iOS implementation in development at the moment?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pauldemarco/flutter_blue/issues/20#issuecomment-350904462>,
or mute the thread

**Comment by HelenGuov** [comment]
Hi @pauldemarco I'm planning to do a PR for this issue. I'm trying to to use CoreBluetooth Objective C framework to implement the native functionality, but I can't seem to figure out a way to install the new framework into ios Flutter. Do you have any resources for this? 
Thanks

**Comment by zerox1212** [comment]
Is there a branch for this somewhere? Is it possible to just port cordova iOS plugin? 
https://github.com/don/cordova-plugin-ble-central

**Comment by pauldemarco** [comment]
I designed the API with both Android and iOS in mind, it should be fairly straight forward to implement.  I unfortunately don't have the time or the Objective-C experience to get this done at the moment.

Feel free to send PR's :+1:

**Comment by zerox1212** [comment]
I don't know Objective-C either, but the Cordova plugin has a very similar API and is Apache 2.0 licensed. If someone could take a look and see if this could speed up implementation it would be great.

**Comment by zerox1212** [comment]
I looked into it more and I think if someone can implement just one of the methods (such as `scan`) I could figure out the rest.

**Comment by pauldemarco** [comment]
The majority of functionality has been implemented for iOS, with the exception of a couple minor issues needing Dart and Android changes as well.

I'll be closing this, please open up new issues if you run into iOS bugs.

Thanks everyone for your patience!
