### ISSUE TITLE
How to get the (preferred/current) MTU?

### ISSUE THREAD

**Issue by paulreimer** [pauldemarco/flutter_blue#224]
For optimal TX segment size, I would like to obtain the current MTU setting, but I'm not sure how to do this via the `flutter_blue` API.

**Comment by pbaker5** [comment]
@paulreimer Did you find a solution for this?

**Comment by paulreimer** [comment]
No, unfortunately I wasn't able to get the actual MTU -- I am still using a default MTU of 23 to be safe (but would very much like to be able to confirm & use a higher MTU).

**Comment by pauldemarco** [comment]
Hi @paulreimer @pbaker5  
This functionality has been added in PR #363 
Please try it out and let me know any feedback.
