### ISSUE TITLE
Can't check if Bluetooth is available

### ISSUE THREAD

**Issue by remygautron** [pauldemarco/flutter_blue#234]
Hi, I have a problem.
I can't check if Bluetooth is available or not, my code :
```dart
FlutterBlue.instance.isAvailable.then((value) => {
      text = "Compatible"
    }).catchError((e) => {
      text = "Incompatible"
    }, test: (e) => e is PlatformException);
```

I always have the error in the console, and my var still null.

**Comment by riccardoratta** [comment]
Can you add the error that you get in the console?

**Comment by riccardoratta** [comment]
This code should work to check when the bluetooth is available; could you try this and see if you get any error?

```dart
FlutterBlue.instance.isAvailable.then((bool isAvailable) {
  if (isAvailable) {
    print('bluetooth is available');
  } else {
    print('bluetooth is NOT available, device may be incompatible');
  }
});
```

**Comment by remygautron** [comment]
> This code should work to check when the bluetooth is available; could you try this and see if you get any error?
> 
> ```dart
> FlutterBlue.instance.isAvailable.then((bool isAvailable) {
>   if (isAvailable) {
>     print('bluetooth is available');
>   } else {
>     print('bluetooth is NOT available, device may be incompatible');
>   }
> });
> ```


The code work thanks !
