### ISSUE TITLE
Installing !ProtoCompiler (3.6.0) curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 60

### ISSUE THREAD

**Issue by lwh2015** [pauldemarco/flutter_blue#236]
![image](https://user-images.githubusercontent.com/16028333/56490903-58ce1780-6519-11e9-9032-96d4a8e61112.png)

**Comment by riccardoratta** [comment]
It may be a network or proxy issue, could you try with a different network?

**Comment by icaglar** [comment]
It's just a curl issue. Update your curl installation to latest version

**Comment by lwh2015** [comment]
> It's just a curl issue. Update your curl installation to latest version

ok，thanks

**Comment by inprise1980** [comment]
How to update curl？

> 
> 
> > It's just a curl issue. Update your curl installation to latest version
> 
> ok，thanks

**Comment by pauldemarco** [comment]
This plugin no longer depends on protoc
