### ISSUE TITLE
onValueChanged characteristic problem

### ISSUE THREAD

**Issue by joaowd** [pauldemarco/flutter_blue#242]
```
_device.onValueChanged(characteristic).listen((List<int> reading){
  //reading length is 1
  ...
}
```

When listening for values changed, I'm only getting the length of 1 on the list I'm receiving, but the device is sending me a list with the length of 8.

I'm receiving that "list" but 1 value at a time, so if the device is sending me a list with <3, 10, 50, 40, 1, 70 , 40, 10>

I receive on the onvaluechanged a list with the value 3, and then a list with the value 10, and then 50...

which delays the data, the device is sending me a new list 10 times a second, so you can imagine, reading one value at a time..

**Comment by phil-tti** [comment]
could you try:
_device.onValueChanged(characteristic).listen((value){
   check list values here rather than casting the return type in listen
})
