### ISSUE TITLE
not found android phone

### ISSUE THREAD

**Issue by azaz0133** [pauldemarco/flutter_blue#261]
i'm used example flutter_blue for test and i scan. but not found devices thai is phone such as another phone that turn ou blutetooth already.

**Comment by ycktw** [comment]
Hi, It seems to be also mentioned in #238 --
You can turn on location service (GPS) first.
And have another try.

**Comment by azaz0133** [comment]
> Hi, It seems to be also mentioned in #238 --
> You can turn on location service (GPS) first.
> And have another try.

i followed uyour suggestion. but it not worked when i scaned i found all devices without ipad iphone and android phone at all. Devices that i found is Mi band3 and any accessories

**Comment by pauldemarco** [comment]
@azaz0133 What type of device are you looking for? Is it a Bluetooth Low Energy device?

**Comment by pauldemarco** [comment]
Stale.
