### ISSUE TITLE
How can I get Bluetooth broadcast data?

### ISSUE THREAD

**Issue by Android1108** [pauldemarco/flutter_blue#298]
How can I get Bluetooth broadcast data?

**Comment by yiguozhen0510** [comment]
@Android1108 Have you solve the problem?i also get the same Issues

**Comment by roryzh** [comment]
I just scan every one second, and use manufacturing data to get the broadcasting data. Hope to find a better method. Because my method is not consistent. Sometimes I can read the broadcast data in 1 second, sometimes it need 2 to 3 seconds.

**Comment by pauldemarco** [comment]
The advertisement data can be retrieved from the scan result, like so:
`result.advertisementData`
