### ISSUE TITLE
Change mtu size and allow flutter to read if the requested size is allowed

### ISSUE THREAD

**Issue by tomcatvr** [pauldemarco/flutter_blue#308]
In the last commit has been added exchangeGattMtu(512, gatt);
It would be very nice if we can set a different size of mtu and then read the BluetoothGattCallback#onMtuChanged callback in flutter so we can write a loop to test the maximum mtu allowed by device.
I mean a loop like:
bool _mtuOk = false;
int _requestedMtu = 512;
_mtuOk = await exchangeGattMtu(_requestedMtu);
while(!_mtuOk ){
 _requestedMtu = _requestedMtu / 2;
 _mtuOk = await exchangeGattMtu(_requestedMtu);
}

**Comment by pauldemarco** [comment]
Hi @tomcatvr 
This functionality has been added in PR #363 
Please try it out and let me know what you think.
