### ISSUE TITLE
[0.6.0+1] miss api with onStateChanged

### ISSUE THREAD

**Issue by Chgocn** [pauldemarco/flutter_blue#314]
With 0.5.0,FlutterBlue and BluetoothDevice all have the api onStateChanged,so I can listen the state changed.But now I can't find it.

**Comment by Chgocn** [comment]
Ok,I find it.It merge to method state.

**Comment by tanliubin** [comment]
Hello, I have the same problem. Can you tell me how to solve it? @Chgocn
