### ISSUE TITLE
CocoaPods minimum required version 1.6.0

### ISSUE THREAD

**Issue by Georgeskh** [pauldemarco/flutter_blue#318]
Warning: CocoaPods minimum required version 1.6.0 or greater not installed. Skipping pod install.
But I have a higher version of CocoaPods installed.
![Screen Shot 2019-07-19 at 5 42 18 PM](https://user-images.githubusercontent.com/49345041/61543883-fe2b5580-aa4c-11e9-905e-89267f47fc7f.png)

**Comment by pauldemarco** [comment]
Please update to the latest cocoa pods and use flutter stable.
