### ISSUE TITLE
How can I send and receive long strings with more than 150 chars?

### ISSUE THREAD

**Issue by KevinRohn** [pauldemarco/flutter_blue#323]
Is it possible to use a buffer to send and receive more than 150 characters on one request?

**Comment by xuzhengquan** [comment]
You can set mtu size.

**Comment by KevinRohn** [comment]
Thank you for the fast response. 
Where can I do this? directly from the flutter_blue package?

**Comment by xuzhengquan** [comment]
Yes, you can read other's PR.

**Comment by xuzhengquan** [comment]
> Thank you for the fast response.
> Where can I do this? directly from the flutter_blue package?
Yes, you can read other's PR.
