### ISSUE TITLE
startScan/discoverServices UUID Service Filter lists

### ISSUE THREAD

**Issue by pauldemarco** [pauldemarco/flutter_blue#34]
startScan and discoverServices should support the ability to filter by service UUIDs.

**Comment by jack4git** [comment]
Aha -- I had assumed since the call flutterBlue.scan included the list of Guids that this was in place. This explains why filtering isn't happening.

I'll need this capability for my app to use flutter_blue ...

**Comment by pauldemarco** [comment]
Closing in favor of #61 and #35

**Comment by jack4git** [comment]
Paul, not sure why this was closed? Are you rolling this functionality into another open issue?

**Comment by jack4git** [comment]
Thanks Paul. I was a bit confused because the Core Bluetooth doc you linked to there doesn’t relate to filtering scanned devices by service uuid.

**Comment by pauldemarco** [comment]
You're right! I split into a separate issue #64 

Thanks for the heads up
