### ISSUE TITLE
Conflict with flutter_workmanager plugin

### ISSUE THREAD

**Issue by edsonboldrini** [pauldemarco/flutter_blue#366]
Yesterday, I open [this issue](https://github.com/vrtdev/flutter_workmanager/issues/66) at flutter_workmanager repository and the dev answered me saying the problem is in the flutter_blue plugin. Could someone help me to find a solution?

**Comment by pauldemarco** [comment]
This should be working with the recently added support for Android V2 embedding.

**Comment by edsonboldrini** [comment]
Thanks!
