### ISSUE TITLE
Notification listen, everytime the value only returns 20 bytes

### ISSUE THREAD

**Issue by hungyip** [pauldemarco/flutter_blue#370]
Hi,

I am using a BLE5.0 device and it is supposed to be able to get more than 20 bytes at a time. How can I change the size of the listen value so that I can get more bytes at a time?

Thanks,

**Comment by ricksondpenha** [comment]
Hi.. change the mtu size by request mtu method

**Comment by pauldemarco** [comment]
You can request an increase in mtu size like so:
```dart 
await device.requestMtu(123);
```

Please note this is only available for Android devices; iOS will automatically negotiate the MTU size.
