### ISSUE TITLE
Didn't open Bluetooth operation?

### ISSUE THREAD

**Issue by DearBo7** [pauldemarco/flutter_blue#380]
Didn't open Bluetooth operation?

**Comment by Blezzing** [comment]
It is quite unclear what problem you are seeing. Can you please elaborate:
What did you try to do, and how?
What did you expect to happen?
What happened?

**Comment by pauldemarco** [comment]
@DearBo7

We will need more information to try and assist you. Please supply a step by step on how to reproduce, and any code that you can share.
