### ISSUE TITLE
Can I add one to get a paired Bluetooth list?

### ISSUE THREAD

**Issue by DearBo7** [pauldemarco/flutter_blue#381]
Can I add one to get a paired Bluetooth list?

**Comment by pauldemarco** [comment]
@DearBo7

GitHub issues are meant for reporting bugs with the library. I would recommend asking questions on StackOverflow where it can be indexed and used as a reference for others.

Thanks.

**Comment by Ahmadre** [comment]
@pauldemarco disagree. This is called a [FEATURE] Request.
