### ISSUE TITLE
how to view only the devices with my uuid for eg uuid-000000-000-0000-0000 

### ISSUE THREAD

**Issue by sonychoudhary** [pauldemarco/flutter_blue#385]
i want to see only the beacons with my uuid on the application

**Comment by kschulz-samsung** [comment]
use the withServices: argument for scan function.
Flutterblue.scan(scanmode:ScanMode.balanced, withServices: [Guid(00000-0000-000-000-00)]);
replace 0000 with your uuid.

**Comment by pauldemarco** [comment]
@sonychoudhary 
You can also use dart's built-in filter functionality for streams:
```dart
services.where((s) => s.uuid == someUuid)
```

In the future, please consider using a public forum like StackOverflow to ask questions, so they can be indexed and help others.
