### ISSUE TITLE
requestMtu on iOS not implemented? maybe fix documentation

### ISSUE THREAD

**Issue by kschulz-samsung** [pauldemarco/flutter_blue#395]
Hi,
According to the readme/frontpage both android and iOS version has support for requestMtu  in flutterBlue. 
When I however test it in my iOS app I get an exception about it not being supported. I checked the code and it does look like it is flutterBlue throwing that particular exception:
https://github.com/pauldemarco/flutter_blue/blob/master/ios/Classes/FlutterBluePlugin.m#L252

If I look into the Bluetooth Core documentation it does seem like this is correctly not supported as iOS wants to try to be smart and negotiate it by itself. 

Maybe this should be a bit better documented in flutter_blue as it seems like it is possible to set the mtu on iOS.  Also it would be nice to have a method to get the negotiated mtu size.

**Comment by pauldemarco** [comment]
You can receive the negotiated MTU size through the “mtu” stream.
