### ISSUE TITLE
error: package androidx.core.app does not exist

### ISSUE THREAD

**Issue by Jbz797** [pauldemarco/flutter_blue#402]
Since the 0.6.3 update, i have this error message and i can't build my app :

`/home/***/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_blue-0.6.3/android/src/main/java/com/pauldemarco/flutter_blue/FlutterBluePlugin.java:43: error: package androidx.core.app does not exist
import androidx.core.app.ActivityCompat;`

**Comment by gitjohnmoon1234** [comment]
Do you have history version to download ? such as v 0.6.2   

![image](https://user-images.githubusercontent.com/37401617/67083558-ef7c4800-f1cd-11e9-8d95-5853874ffc92.png)

**Comment by Jbz797** [comment]
Okay, but what should I do?

**Comment by gitjohnmoon1234** [comment]
> Okay, but what should I do?
could you send me a history version? whitch can run without androidx

**Comment by kamilk91** [comment]
Yes its todays error. Just use older version and wait for author response.

**Comment by Jbz797** [comment]
ok thanks

**Comment by KevinRohn** [comment]
> Okay, but what should I do?

Just use an older version in the pubspec.yaml flutter_blue: ^0.6.2

**Comment by kamilk91** [comment]
@KevinRohn  that was my advice, but i have problem now.. I tried to use 0.6.3, and when i switched to 0.6.2 and pub get i have

```
  location: class FlutterBluePlugin
C:\Users\kamil\Desktop\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_blue-0.6.3\android\src\main\java\com\pauldemarco\flutter_blue\FlutterBluePlugin.java:152: error: cannot find symbol
                    ActivityCompat.requestPermissions(
                    ^
  symbol:   variable ActivityCompat
  location: class FlutterBluePlugin
Note: C:\Users\kamil\Desktop\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_blue-0.6.3\android\src\main\java\com\pauldemarco\flutter_blue\FlutterBluePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\kamil\Documents\bluetoothmanageriqos\build\flutter_blue\generated\source\proto\debug\javalite\com\pauldemarco\flutter_blue\Protos.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors

FAILURE: Build failed with an exception.
```

Why its strill trying to use 0.6.3?

**Comment by Jbz797** [comment]
I have downgraded successful. I put a fixed version in my pubspec.yaml : `flutter_blue: 0.6.2`.
Have you tried a `flutter clean` ?

**Comment by kamilk91** [comment]
@Jbz797  yes i tried both, clean and change pubspec. i tried even 0.5.0 and delete folder flutter_blue.0.6.3 from cache

**Comment by kamilk91** [comment]
Okay it was my mistake, i had to use ```flutter_blue: 0.6.2``` instead of ```flutter_blue: ^0.6.2 ```

**Comment by pauldemarco** [comment]
Could it be because your project has outdated Android project files?

Run flutter upgrade 
Remove android and iOS folders in your project
Run “flutter create .” within your project to get new android project files

**Comment by wadekb** [comment]
I just created a new Flutter project in Android Studio 3.5.1 and pulled in 0.6.3 and got the error.  Version from flutter doctor -

Flutter (Channel stable, v1.9.1+hotfix.5

**Comment by alexcode9** [comment]
Same for me...
0.6.2 works, 0.6.3 breaks project with these errors
even on a clean new project created using `flutter create --androidx`

**Comment by vincentsong** [comment]
@pauldemarco I got she same issue when try to build Android version

**Comment by maheshwara-bwd** [comment]
@pauldemarco I too got the same issue in 0.6.3,
I also tried the same by running your example by cloning the flutter_blue repo, Still the same issue

**Comment by KevinRohn** [comment]
Same problem here. 0.6.3 doesn't work for Android. I downgraded to 0.6.2 which works fine.

**Comment by ElArtista** [comment]
Yep same here

**Comment by MarkusPayne** [comment]
Can confirm same issue with 0.6.3.  I also tried cloning the repo and trying the example app.  0.6.2 does work for me.

**Comment by yudhiApp** [comment]
I am new to flutter and have a fresh installation of android studio and flutter. I tried everthing mentioned in this thread but I get all kind many errors. I did what they instructed here https://github.com/pauldemarco/flutter_blue/issues/125, it did not work too. 

Can anyone summarise how to get flutter_blue to work step by step from scratch?

**Comment by maheshwara-bwd** [comment]
Please try adding the required androidx dependencies in gradle file

android/build.gradle:

dependencies {
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.core:core:1.1.0'
}

**Comment by yudhiApp** [comment]
This might help others. I do not receive this error anymore **"package androidx.core.app does not exist**  
I have managed to make the example work as follows:
1. I created a new flutter project in android studio.
2. I deleted the test folder and deleted the main.dart in the lib folder.
3. I copied the main.dart and widgets.dart files found in "example/lib/" from the master repository to my lib folder.
4. Next I added   flutter_blue: 0.6.2 underneath cupertino_icons: ^0.1.2 in the dependencies in the pubspec.yaml and clicked packages get.
5. In android > app > build.gradle, I changed  minSdkVersion 16 to 19. 
6. Run it on my phone, got a couple of deprecation messages. The app runs fine and I can connect to the BLE device.

I need to mention that the new project I created was not automatically created in androidx and I did not migrate to androidx using Refactor.
I am new o flutter and the app dev world, will not migrating to androidx be a problem?

**Comment by Jbz797** [comment]
The version of 'flutter_blue' that is a problem is version "0.6.3". And you have installed the "0.6.2".

**Comment by Jbz797** [comment]
Some news about this issue ?

**Comment by rjcasson** [comment]
I made a pull request (#416), but you can quickly fix this issue by adding the following line to the dependencies in android/build.grade of the flutter_blue plugin:

`implementation "androidx.core:core:1.1.0"`

**Comment by 00believers00** [comment]
> I made a pull request (#416), but you can quickly fix this issue by adding the following line to the dependencies in android/build.grade of the flutter_blue plugin:
> 
> `implementation "androidx.core:core:1.1.0"`

it's work!!
thanks

**Comment by PhilColbert** [comment]
Thanks and thanks for paul for creating this plugin, nice one :)

**Comment by KevinRohn** [comment]
Thank you this works for me!

**Comment by CedYF** [comment]
I get could not find implementation @rjcasson

**Comment by PhilColbert** [comment]
Maybe added in the wrong place , I did first.

Make sure its in the flutter blue package and not your own.

 in dir :- flutter\.pub-cache\hosted\pub.dartlang.org\flutter_blue-0.6.3+1\android

**Comment by bus710** [comment]
The solution sounds like....

In ~/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_blue-0.6.3+1/android/build.gradle,

At the line of 80, I could find: 
```
dependencies {
     implementation 'com.google.protobuf:protobuf-lite:3.0.1'
     implementation "androidx.core:core:1.1.0" // Add this line there.
}
```

**Comment by pauldemarco** [comment]
Please follow the instructions here and let me know your results:
https://github.com/pauldemarco/flutter_blue/issues/415#issuecomment-548186492

**Comment by jiyangjjj** [comment]
> @KevinRohn that was my advice, but i have problem now.. I tried to use 0.6.3, and when i switched to 0.6.2 and pub get i have
> 
> ```
>   location: class FlutterBluePlugin
> C:\Users\kamil\Desktop\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_blue-0.6.3\android\src\main\java\com\pauldemarco\flutter_blue\FlutterBluePlugin.java:152: error: cannot find symbol
>                     ActivityCompat.requestPermissions(
>                     ^
>   symbol:   variable ActivityCompat
>   location: class FlutterBluePlugin
> Note: C:\Users\kamil\Desktop\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_blue-0.6.3\android\src\main\java\com\pauldemarco\flutter_blue\FlutterBluePlugin.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: C:\Users\kamil\Documents\bluetoothmanageriqos\build\flutter_blue\generated\source\proto\debug\javalite\com\pauldemarco\flutter_blue\Protos.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 4 errors
> 
> FAILURE: Build failed with an exception.
> ```
> 
> Why its strill trying to use 0.6.3?

I download 0.6.2 and changed the url in .packages to use 0.6.2.

**Comment by tomcatvr** [comment]
> Please follow the instructions here and let me know your results:
> [#415 (comment)](https://github.com/pauldemarco/flutter_blue/issues/415#issuecomment-548186492)

Hi,
I've deleted and recreated the android project as mentioned in the link
Fluttersi: Channel master, v1.10.15-pre.404,
My flutter_blue build.gradle plugin is now:
dependencies {
    implementation 'com.google.protobuf:protobuf-lite:3.0.1'
    implementation 'androidx.core:core:1.1.0'
    implementation 'androidx.appcompat:appcompat:1.1.0'
}

But I still get an error:
error: incompatible types: Activity cannot be converted to AppCompatActivity
wich points to line 83 of FlutterBluePlugin.java
81    FlutterBluePlugin(Registrar r){
82        this.registrar = r;
83        this.activity = r.activity();

error is: 
incompatible types:
Required: androidx.appcompat.app.AppCompatActivity
Found: android.app.Activity

r.activity() is an Activity while this.activity is declared as AppCompatActivity
If at line 64 (og FlutterBluePlugin.java) I declare activity as Activity
before
private final AppCompatActivity activity;
now
private final Activity activity;

it works but I'm not sure if is the right way

**Comment by bus710** [comment]
@tomcatvr,
Just want to know that if there is the pubspec.lock file.
I had the same error even after I followed the steps @pauldemarco provided. 
That was because the instruction introduces the steps from ground but from an existing project.

**Comment by tomcatvr** [comment]
@bus710 
Yes, there is the pubspec.loc file.
I've recreated the project without it but still getting the same problem

**Comment by bus710** [comment]
@tomcatvr,
I mean... you may delete the lock file if you try building from an existing project.

Anyway, I tried by myself as the instruction provided (#415) and this is the end result:

```
$ flutter build apk
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK
to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:
        https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Note: /home/bus710/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_blue-0.6.3+1/android/src/main/java/com/pauldemarco/flutter_blue/FlutterBluePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: /home/bus710/Desktop/aa/build/flutter_blue/generated/source/proto/release/javalite/com/pauldemarco/flutter_blue/Protos.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                      
Removed unused resources: Binary resource data reduced from 41KB to 34KB: Removed 17%
Running Gradle task 'assembleRelease'...                                
                                                   
Running Gradle task 'assembleRelease'... Done                     130.0s (!)
✓ Built build/app/outputs/apk/release/app-release.apk (15.3MB).
```

My environment: 

```
$ flutter --version

Flutter 1.10.15-pre.408 • channel master • https://github.com/flutter/flutter.git
Framework • revision 7d03371610 (72 minutes ago) • 2019-11-05 08:57:25 -0800
Engine • revision 7b968ff95f
Tools • Dart 2.7.0
```

**Comment by bus710** [comment]
@tomcatvr,
I mean... you may delete the lock file if you try building from an existing project.

Anyway, I tried by myself as the instruction provided (#415) and this is the end result:

```
$ flutter build apk
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK
to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:
        https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Note: /home/bus710/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_blue-0.6.3+1/android/src/main/java/com/pauldemarco/flutter_blue/FlutterBluePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: /home/bus710/Desktop/aa/build/flutter_blue/generated/source/proto/release/javalite/com/pauldemarco/flutter_blue/Protos.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                      
Removed unused resources: Binary resource data reduced from 41KB to 34KB: Removed 17%
Running Gradle task 'assembleRelease'...                                
                                                   
Running Gradle task 'assembleRelease'... Done                     130.0s (!)
✓ Built build/app/outputs/apk/release/app-release.apk (15.3MB).
```

My environment: 

```
$ flutter --version

Flutter 1.10.15-pre.408 • channel master • https://github.com/flutter/flutter.git
Framework • revision 7d03371610 (72 minutes ago) • 2019-11-05 08:57:25 -0800
Engine • revision 7b968ff95f
Tools • Dart 2.7.0
```

**Comment by tomcatvr** [comment]
@bus710 
Thanks for the info. I've recreted once more the project and this time worked!
Maybe after deleting pubspec.lock I did not call flutter clean and so I was using a previous version of the library which used AppCompatActivity (but is only an hypothesis)
