### ISSUE TITLE
Api to get phone BLE device id

### ISSUE THREAD

**Issue by hanabi1224** [pauldemarco/flutter_blue#413]
That would be useful too, is there plan to add that api?

**Comment by ericstephen** [comment]
You get a BluetoothDevice from your scan method and that BluetoothDevice has an id property which is the Device Identifier. What else are you looking for?

**Comment by hanabi1224** [comment]
@ericstephen I mean the ble mac id of the phone itself

**Comment by yiguozhen0510** [comment]
@hanabi1224 have you Solvethe Problem?

**Comment by pauldemarco** [comment]
The ble Mac ID is not exposed on all platforms for security reasons (iOS).  The typical workaround for this is to include it in Advertisment data or characteristic value.
