### ISSUE TITLE
How to Send Advertising ?

### ISSUE THREAD

**Issue by ShadowOfWhite** [pauldemarco/flutter_blue#414]
I can receive the Advertisement,but how to Send Advertising ?

**Comment by ericstephen** [comment]
Not sure you understand the nature of Advertisement Data or I am missing something. You don't send advertisement data. It's something you listen for. If you want to write something to a device you will need to set up services and characteristics in order to perform writes.

**Comment by ShadowOfWhite** [comment]
> Not sure you understand the nature of Advertisement Data or I am missing something. You don't send advertisement data. It's something you listen for. If you want to write something to a device you will need to set up services and characteristics in order to perform writes.

Obviously,i can listen Advertisement Data ,but I also should be able to send Advertisement data.Im an Android Devolper,in the Android, call BluetoothLeAdvertiser#startAdvertising can send  advertisement data,so i wish this awesome plugin support send advertisement data,thanks.

**Comment by yiguozhen0510** [comment]
How can I receive the Advertisement Data?what,s the method?

**Comment by ShadowOfWhite** [comment]
@yiguozhen0510 
// Listen to scan results
var subscription = flutterBlue.scanResults.listen((scanResult) {
    // do something with scan result
    device = scanResult.device;
    print('${device.name} found! rssi: ${scanResult.rssi}');
});
scanResult is the Advertisement Data

**Comment by yiguozhen0510** [comment]
Hello:
    I am grad to here your e-mail and thank you very much.The Advertisement Data for Android we can get it,but IOS.and now We find the preblem beacuse the blueDevice send data for a mistake,and blueDevice doesn't return the data by  standard format，as a result we can't get the  Advertisement Data.But angway,Thanks a lot.Good Luck!






At 2019-11-26 15:18:18, "白色的影子" <notifications@github.com> wrote:


@yiguozhen0510
// Listen to scan results
var subscription = flutterBlue.scanResults.listen((scanResult) {
// do something with scan result
device = scanResult.device;
print('${device.name} found! rssi: ${scanResult.rssi}');
});
scanResult is the Advertisement Data

**Comment by Akilesh30** [comment]
how to broadcast my own id to other devices?
