### ISSUE TITLE
Android targeting sdk version 29 not working with version 0.6.3+1

### ISSUE THREAD

**Issue by tomcatvr** [pauldemarco/flutter_blue#433]
Hi,
if I switch to targetSdkVersion 29, the example starts but when I search for devices it does not found any.

Step to reproduce:
- use Flutter 1.9.1+hotfix.6 • channel stable
- download example
- add implementation "androidx.core:core:1.1.0" in build.gradle so we can use flutter stable channel
- switch to targetSdkVersion 29.
Same behaviour if I use flutter master channel

**Comment by rjcasson** [comment]
Do you happen to using a device running Android 10? I ran into this issue a few weeks back and made a pull request that fixed it on my end: #383

**Comment by tomcatvr** [comment]
@rjcasson Yes, thanks! I'm running Android 10.
Waiting for the update I'll compile with targetSdkVersion 28.

**Comment by tomcatvr** [comment]
@rjcasson Yes, thanks! I'm running Android 10.
Waiting for the update I'll compile with targetSdkVersion 28.
