### ISSUE TITLE
@UiThread must be executed on the main thread

### ISSUE THREAD

**Issue by moti0375** [pauldemarco/flutter_blue#435]
Hi,

I've tried to use it but i am getting this exception when trying to connect a device:
@UiThread must be executed on the main thread

You may look at my code in my repo:
https://github.com/moti0375/FlutterBDT

The code for BT connection is in the bloc file and in bluetooth package.

Thanks,
Moti.

**Comment by d-wolf** [comment]
The same question was answered in #450 .

**Comment by pauldemarco** [comment]
This should be resolved with the recent support for Android v2 embedding.
