### ISSUE TITLE
How can I remember the last bluetooth device connected?

### ISSUE THREAD

**Issue by borisllona** [pauldemarco/flutter_blue#436]
I'm trying to develop something that needs to connect to the device the first time, then remember the choice and connect-it automaticaly. How can I do that?
I've been seen that flutter shared preferences is an option but we can't save objects so not possible for my case.
Any suggestion?
Thanks so much!

**Comment by ValterBarbosaS** [comment]
Our friend here has a good example https://github.com/moti0375/FlutterBDT
