### ISSUE TITLE
[Android]Methods marked with @UiThread must be executed on the main thread. Current thread: Binder:19970_4

### ISSUE THREAD

**Issue by yiguozhen0510** [pauldemarco/flutter_blue#450]
when i call the connect(),i can't receive the state of bluetooth by used onStateChanged.anyone got this?

**Comment by pauloamaral93** [comment]
If you are using Flutter > 1.9 and flutter_blue < 6.0 you will find this problem.

**Comment by yiguozhen0510** [comment]
so,What can i do for it?

**Comment by pauloamaral93** [comment]
Downgrade flutter or upgrade flutter_blue (breaking changes can happen)

**Comment by d-wolf** [comment]
Duplicate of #435 .

**Comment by pauldemarco** [comment]
This should be resolved with the recent support for Android v2 embedding.
