### ISSUE TITLE
Write Characteristic withoutResponse: true does not return Future<Null> immediately as described

### ISSUE THREAD

**Issue by akatriel** [pauldemarco/flutter_blue#451]
I'm chaining calls like this:
`listOfBLE_Services.last.characteristics.last.write(someAction, withoutResponse: true).then((val) => _logTheAction))`

But, `write` never returns, so my subsequent `then` is never called.

May be related to issue #345 or #311

**Comment by pauldemarco** [comment]
Does the characteristic end up being written? As in, if you check from the peripheral side, do you see the updated value?

**Comment by akatriel** [comment]
I'm no longer working on this project, so I won't be able to reproduce.

**Comment by pauldemarco** [comment]
Ok we’ll close this for now.
