### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by jj89757hhb** [pauldemarco/flutter_blue#457]
Launching lib/main.dart on iPhone 8 in debug mode...
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `flutter_blue` from `.symlinks/plugins/flutter_blue/ios`

**Comment by pauldemarco** [comment]
Hi @jj89757hhb,
Can you elaborate on the issue you are facing?

I have just commited a fix that might affect you, please try by targeting the master branch of flutter_blue in your **pubspec.yaml**:
```
dependencies:
  flutter_blue:
    git: git://github.com/pauldemarco/flutter_blue.git
```
