### ISSUE TITLE
How to convert a hexadecimal array to bytedata?

### ISSUE THREAD

**Issue by cander0815** [pauldemarco/flutter_blue#472]
Bluetooth communication is a bytedata array, right?

How should I transform it?

**Comment by Blaxou** [comment]
@cander0815 This has nothing to do with FlutterBlue, just google your issue or go to StackOverflow :P

**Comment by pauldemarco** [comment]
Hi @cander0815 this question would be better suited on StackOverflow.

If you are experiencing a bug with the plugin, please reopen by sharing some code and describing the exact issue you are facing.

Thanks.
