### ISSUE TITLE
Want to connect to a specific device

### ISSUE THREAD

**Issue by bobosette** [pauldemarco/flutter_blue#473]
Hi everybody. I'm implementing flutter blue on my project. In my app I just would like to connect to a specific device and, like in this comment https://github.com/pauldemarco/flutter_blue/issues/125#issuecomment-432684180 , i could put a control on the device name.
Unfortunately, in the main.dart i don't find the method _startScan().
Somebody has any idea???

Thank you

**Comment by jeremy110** [comment]
I know how to show the specific devices.You can find the codes on flutter blue widget.
![1578914428485](https://user-images.githubusercontent.com/52516810/72252568-78264b00-363a-11ea-8946-6a70ac4b1c88.jpg)
![1578914490667](https://user-images.githubusercontent.com/52516810/72252569-78264b00-363a-11ea-9fed-18ea2bd83d23.jpg)

**Comment by bobosette** [comment]
Thank u. I already found a solution
