### ISSUE TITLE
RxDart Version incompatibility

### ISSUE THREAD

**Issue by saulopef** [pauldemarco/flutter_blue#477]
Recently we need to upgrade the version of rxdart library, but during this process this massage have ocurred:

> [fitwiz_app] flutter packages get
> Running "flutter pub get" in fitwiz_app...                      
> Because flutter_blue >=0.6.0 depends on rxdart ^0.22.0 and fitwiz_app depends on rxdart 0.23.1, flutter_blue >=0.6.0 is forbidden.
> 
> So, because fitwiz_app depends on flutter_blue ^0.6.3+1, version solving failed.
> pub get failed (1; So, because fitwiz_app depends on flutter_blue ^0.6.3+1, version solving failed.)
> exit code 1

Aparently, the flutter_blue depends the rxdart 0.22.0 version, but when we remove the rxdart of the pubspec, no one error has ocurred, why this is happening? how can I upgrade this 2 libraries?

![image](https://user-images.githubusercontent.com/35967830/72174930-a1847400-33b9-11ea-82e8-807b11f8e62a.png)

rxdart: "0.23.1"
flutter_blue: ^0.6.3+1

**Comment by saulopef** [comment]
Temporarily solved by using dependency_overrides.

**Comment by mciekurs2** [comment]
Same problem here but with bloc. Is there any temporary solutions I can do to fix it?

**Comment by madc** [comment]
@mciekurs2 My temp. solution is getting the current master branch of flutter blue:
```
  flutter_blue:
    git:
      url: git://github.com/pauldemarco/flutter_blue.git
      ref: master
```
Not yet sure, if everything works properly tough.

**Comment by madc** [comment]
Just a quick update: Everything seems to work fine from master (for now).

**Comment by saulopef** [comment]
yes, using Master seems to be a great solution for now, closing this, and wait for version actualization.
