### ISSUE TITLE
iOS no issue but android  one characteristic notify and  one characteristic write invoke together will  throws Exception

### ISSUE THREAD

**Issue by loveQingQing** [pauldemarco/flutter_blue#479]
E/flutter ( 1741): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(write_characteristic_error, writeCharacteristic failed, null)
E/flutter ( 1741): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 1741): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter ( 1741): <asynchronous suspension>
E/flutter ( 1741): #2      BluetoothCharacteristic.write (package:flutter_blue/src/bluetooth_characteristic.dart:123:10)
E/flutter ( 1741): #3      BlueToothManager.blueToothConnect.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:jjaj/bluetooth_tool/bluetooth_manager.dart:145:31)
E/flutter ( 1741): #4      List.forEach (dart:core-patch/growable_array.dart:285:8)
E/flutter ( 1741): #5      BlueToothManager.blueToothConnect.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:jjaj/bluetooth_tool/bluetooth_manager.dart:88:27)
E/flutter ( 1741): #6      _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter ( 1741): #7      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 1741): #8      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
E/flutter ( 1741): #9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
E/flutter ( 1741): #10     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
E/flutter ( 1741): #11     Future._complete (dart:async/future_impl.dart:514:7)
E/flutter ( 1741): #12     _cancelAndValue (dart:async/stream_pipe.dart:65:12)
E/flutter ( 1741): #13     Stream.first.<anonymous closure> (dart:async/stream.dart:1253:11)
E/flutter ( 1741): #14     _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter ( 1741): #15     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 1741): #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter ( 1741): #17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
E/flutter ( 1741): #18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
E/flutter ( 1741): #19     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:134:11)
E/flutter ( 1741): #20     _MapStream._handleData (dart:async/stream_pipe.dart:234:10)
E/flutter ( 1741): #21     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:166:13)
E/flutter ( 1741): #22     _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter ( 1741): #23     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 1741): #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter ( 1741): #25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
E/flutter ( 1741): #26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
E/flutter ( 1741): #27     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:134:11)
E/flutter ( 1741): #28     _MapStream._handleData (dart:async/stream_pipe.dart:234:10)
E/flutter ( 1741): #29     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:166:13)
E/flutter ( 1741): #30     _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter ( 1741): #31     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 1741): #32     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter ( 1741): #33     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
E/flutter ( 1741): #34     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
E/flutter ( 1741): #35     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:134:11)
E/flutter ( 1741): #36     _WhereStream._handleData (dart:async/stream_pipe.dart:209:12)
E/flutter ( 1741): #37     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:166:13)
E/flutter ( 1741): #38     _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter ( 1741): #39     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 1741): #40     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter ( 1741): #41     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
E/flutter ( 1741): #42     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
E/flutter ( 1741): #43     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:134:11)
E/flutter ( 1741): #44     _MapStream._handleData (dart:async/stream_pipe.dart:234:10)
E/flutter ( 1741): #45     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:166:13)
E/flutter ( 1741): #46     _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter ( 1741): #47     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 1741): #48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter ( 1741): #49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
E/flutter ( 1741): #50     _BufferingStreamSubscription

**Comment by loveQingQing** [comment]
sometimes log this:
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(write_characteristic_error, writeCharacteristic failed, null)
E/flutter (32468): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (32468): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (32468): <asynchronous suspension>
E/flutter (32468): #2      BluetoothCharacteristic.write (package:flutter_blue/src/bluetooth_characteristic.dart:123:10)

**Comment by pauldemarco** [comment]
What steps are you taking to see the error?

Can you share the code that’s causing it?

Feel free to create another ticket with the above.
