### ISSUE TITLE
Double notifications when re-connecting

### ISSUE THREAD

**Issue by MrHazee** [pauldemarco/flutter_blue#481]
Hi,
Thanks for all your wonderful work @pauldemarco 
I am experiencing trouble like #317 but the fix doesnt work for me. This occurs when I reconnect to my nrf 52 DK after loosing connection. It doesnt matter if I disconnect manually by (running await device.disconnect()) or if I am forcing a disconnect by restarting the nrf 52 DK. In issue #317 the soulution seems to be:
222: gattServer.disconnect();
223: gattServer.close();  // also removes listeners! 
Can I somehow achieve this from within flutter?
I´ve put in a couple of days in this but no matter what, I cant get around it.. even tried to restart the app with flutter_reset and then reconnect but with no success..
Thanks /Rasmus

**Comment by HipSze** [comment]
I have the same issue. When disconnect the device and connect again, it will have double notifications.

**Comment by tomcatvr** [comment]
Same problem here

**Comment by aitch-3** [comment]
Same problem here. 

issue reproduce:
1. connect peripheral(1).
2. disconnect peripheral(1).
3. connect other peripheral(2).
4. disconnect peripheral(2).
5. connect to the first peripheral(1) again.

the very first peripheral connected emits double notification values.

if more than 1 peripheral gets connected, (peripheral(2), peripheral(3), peripheral(4).....) the first peripheral will emit multiple notification values.

**Comment by aitch-3** [comment]
> if more than 1 peripheral gets connected, (peripheral(2), peripheral(3), peripheral(4).....) the first peripheral will emit multiple notification values.

So, i checked again, the problem was on my end.

 the `setNotifyValue(false)` was never called. And the next time I try to  call `setNotifyValue(true)` then `setNotifyValue(false)` gets called. 

Since I can't use await in `dispose()` function, I had to use `then((_) {})` to stop notification.

**Comment by MrHazee** [comment]
I was able to solve this (tack Per) by making sure every listener really is canceled on disconnect().

subscription = listen((){});
subscription.cancel()

The problem was on my end and not flutter_blue.

**Comment by zwells** [comment]
I'm having the same issue, can somebody post an example of their disconnect function that fixed this?

**Comment by zwells** [comment]
Found my issue. I didn't set _rx.value.listen() to a StreamSubscription so that I could properly call .cancel();
