### ISSUE TITLE
Android X ScanResult empty list

### ISSUE THREAD

**Issue by KevinRohn** [pauldemarco/flutter_blue#486]
Hello community,

I'm using Android X and Android 9 devices for testing. 
For Android X I've a huge problem. The ScanResults are always empty. On Android 9 Devices it shows me the correct ScanResults. 

Same Project. compileSDKVersion is 29. I also tried to change the permissions from  ACCESS_COARSE_LOCATION to ACCESS_FINE_LOCATION, but no changes. 

Does someone have any idea how to fix it? 

Thank you in advance
cheers,
Kevin

**Comment by tomcatvr** [comment]
Hi, there is still a bug in this version. I read it sometime ago.
Android X need ACCESS_FINE_LOCATION but it has to be put in the module permission.
My suggestion is to use compileSDKVersion is 28 till the new version

**Comment by x0054** [comment]
See this pull request:

https://github.com/pauldemarco/flutter_blue/pull/383

It, along with my pull request for fixing similar issue with iOS 13.3 need to be merged in. To the author: please consider merging those 2 requests so that Flutter Blue can target the latest OS builds.

**Comment by KevinRohn** [comment]
@x0054 I tried to implement the changes from your pull request, but it also ends in an empty scan result.

**Comment by KevinRohn** [comment]
Any news? I'm really stuck on the issue.

**Comment by mudlee** [comment]
Same here (osxygenos with android 10)

**Comment by roryzh** [comment]
Same here. My app used to work on my iOS 13.3, then I tested my app on Android 10, my app gives "another scan is already in progress exception". And the scan result list is empty. My app function is scanning for a BLE device that is advertising data without connection required. My app scan for this device once per second to update data since I cannot connect to it.

So I reinstall the example app from flutter_blue, it runs without exception, but the BLE device list is always empty.

**Comment by mudlee** [comment]
@pauldemarco are you still maintain this package? If not, it's OK for sure, just to know if I have to just wait or I have to either fix it or find an another package. Thanks.

**Comment by roryzh** [comment]
@mudlee Please let me know if you find another package. I didn't find one. I am planning to use Swift for now.

**Comment by mudlee** [comment]
> @mudlee Please let me know if you find another package. I didn't find one. I am planning to use Swift for now.

I have not found either, but I'm optimistic :P There is one, but it's still lacks something very basic, see here: https://github.com/PhilipsHue/flutter_reactive_ble/issues/12

**Comment by dokinkon** [comment]
I have some problem. After struggling few hours, I found just change targetSdkVersion to 28 instead 29 can fix this issue. Hope can help you guys.

**Comment by boskokg** [comment]
Note:
I added your code together with other merge request.

  flutter_blue:
    git:
      url: https://github.com/boskokg/flutter_blue.git
      ref: 0.7.1

**Comment by dokinkon** [comment]
@boskokg 
I found current android plugin is not compatible with Flutter 1.12+. I try to migrate to flutter 1.12. If you are interested with this issue, merging into your fork is welcome.

https://github.com/dokinkon/flutter_blue/commit/1b828895330878ed6ccb3e6271ccf0e1a89ae7b2

For your reference
https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

**Comment by boskokg** [comment]
@dokinkon 
I use flutter 1.16.1 and this plugin works in my project (My activity still extends FlutterActivity).

Is your change compatible with both old and new approach? I would not like to cut off the people that cannot migrate to new approach because the still depend on plugins that are not migrated.

**Comment by ride4sun** [comment]
> flutter_blue:
> git:
> url: https://github.com/boskokg/flutter_blue.git

@pauldemarco I am wondering if you could give others access to this repository and merge some of the old merge requests. @boskokg would you willing to do that? I don't have the background unfortunately

**Comment by dokinkon** [comment]
> @dokinkon
> I use flutter 1.16.1 and this plugin works in my project (My activity still extends FlutterActivity).
> 
> Is your change compatible with both old and new approach? I would not like to cut off the people that cannot migrate to new approach because the still depend on plugins that are not migrated.

@boskokg 
Got it. I will take a look into compatible with legacy approaches. Thanks for reminding.

**Comment by pauldemarco** [comment]
@KevinRohn 
This should be resolved in the latest version 0.7.0

**Comment by Mr-xzq** [comment]
I also meet a similar problem in Android X，flutter_blue version is 0.7.3。 

1. You can attempt set 
![image](https://user-images.githubusercontent.com/53166933/142336700-5c889b78-a380-4ffb-9ef7-cab6838a1fa0.png)

2. and after manual open your mobile gps location (this is important)。
