### ISSUE TITLE
Samsung A7 does not see advertisements in app, but does in the Bluetooth settings menu

### ISSUE THREAD

**Issue by Klievan** [pauldemarco/flutter_blue#496]
I'm advertising BLE 4.2 with manufacture specific data 0xFFFF. The app on the phone does not receive the incoming packets, but the external device gets discovered in the Bluetooth settings menu. Are there any obvious reasons for this?

**Comment by KevinRohn** [comment]
Does your device run on Android 10 ?

**Comment by ride4sun** [comment]
No 9

**Comment by Klievan** [comment]
@KevinRohn No. The device is running Android 9 indeed.

**Comment by Fleximex** [comment]
Do you have Location services turned on, on your phone?

**Comment by Klievan** [comment]
This seems to be an issue with the Nordic BLE-chip and some Samsung phones, so I'm suspecting this isn't a Flutter Blue issue. Therefore I'm closing this issue.
