### ISSUE TITLE
Manufacture data missing in Example App?  Where is the raw Advertisement Data found?

### ISSUE THREAD

**Issue by robomike** [pauldemarco/flutter_blue#502]
Hi All, maybe I am just confused.  Here are screen shots of my device in nordic RF and flutter blue , how is the raw data presented in flutter blue ? 
![Screenshot_20200225-162749](https://user-images.githubusercontent.com/4317367/75289353-1ede3980-57ec-11ea-8363-b79dadf08dac.jpg)
![Screenshot_20200225-162447_nRF Connect](https://user-images.githubusercontent.com/4317367/75289362-230a5700-57ec-11ea-89eb-d193f96cb364.jpg)
![Screenshot_20200225-162439_nRF Connect](https://user-images.githubusercontent.com/4317367/75289375-2a316500-57ec-11ea-9d02-c56b716e2acf.jpg)
![Screenshot_20200225-162312](https://user-images.githubusercontent.com/4317367/75289388-31587300-57ec-11ea-8ab7-5fc24811f6fd.jpg)

_Originally posted by @robomike in https://github.com/pauldemarco/flutter_blue/issues/102#issuecomment-591079447_

**Comment by zwells** [comment]
You can get this using device.advertisementData.manufacturerData.toString()

**Comment by pauldemarco** [comment]
Hi @robomike,

As @zwells mentioned, what you are showing in the Flutter Blue screenshot is characteristic data, and in the nRF screenshot Advertisement Data is shown.

You can retrieve the advertisement data from the ScanResult with `scanResult.advertisementData`.
