### ISSUE TITLE
How to read stream of data from Bluetooth LE device 

### ISSUE THREAD

**Issue by mdzafar3194** [pauldemarco/flutter_blue#508]
@pauldemarco, @brianegan, @dustin-graham, @hanabi1224  I'm newbie into flutter and using the same `Repository code`  for scanning the bluetooth device.
I have a Bluetooth device which senses the Air particals and emits data. 

Please help me out in streaming the data from connected device as a terminal data.
Any help would be appreciated!!

**Comment by pauldemarco** [comment]
Questions should be asked on StackOverflow or the discord channel. Github issues should be used for bugs pertaining to the plugin.
