### ISSUE TITLE
Is this just for BLE?

### ISSUE THREAD

**Issue by dawsonc623** [pauldemarco/flutter_blue#512]
Forgive my ignorance, as I am just starting out learning Bluetooth. Is this tool only BLE-compatible, or does it handle classic Bluetooth as well?

**Comment by juliansteenbakker** [comment]
This is only for BLE related activities, not classic Bluetooth.

**Comment by ConProgramming** [comment]
> This is only for BLE related activities, not classic Bluetooth.

Know of any good classic Bluetooth libraries?

**Comment by juliansteenbakker** [comment]
> > This is only for BLE related activities, not classic Bluetooth.
> 
> Know of any good classic Bluetooth libraries?

I would suggest searching on [pub.dev](https://pub.dev/) for all kinds of packages related to flutter. [Take a look at these search results.](https://pub.dev/packages?q=flutter+bluetooth)

**Comment by pauldemarco** [comment]
@dawsonc623 At the present time, this library is focused on Bluetooth Low Energy.

Thanks.
