### ISSUE TITLE
Set Bluetooth name

### ISSUE THREAD

**Issue by ManojMM026** [pauldemarco/flutter_blue#517]
Hello, Library looks very good, Can I set bluetooth name programatically though?

**Comment by pauldemarco** [comment]
Hi @ManojMM026,

Are you referring to the Device Name Characteristic (0x2A00)? If so, you can write to characteristics by calling the `write` method on the characteristic instance.

**Comment by pauldemarco** [comment]
Closing for now. Please consider using StackOverflow for questions, as it can be indexed easily for use by others.
