### ISSUE TITLE
Scan Results running on BLE phone Moto 7g are always empty

### ISSUE THREAD

**Issue by ride4sun** [pauldemarco/flutter_blue#538]
I am using ` flutter_blue: ^0.7.1+1` on flutter beta channel.
I am using a Moto 7g which is a BLE Phone and I don't get any devices in my scan result.
There is no Exception or Error message, no ideas where to go from here.
If I run the same program on IOS I see 3  BLE devices in my scan results. Same flutter version on IOS

**Comment by pauldemarco** [comment]
Are you using any scan filters?

**Comment by ride4sun** [comment]
The IOS and Android program is exactly the same. I do not even know how to set up a filter.

**Comment by ride4sun** [comment]
Added #539 The permissions for Android where missing. @pauldemarco Is there a way to throw an exception when the permissions are missing

**Comment by RafaRuiz** [comment]
I still see no results and I'm still able to install the app from Google Play
