### ISSUE TITLE
Scanresult device id on iOS shows a long ID

### ISSUE THREAD

**Issue by KevinRohn** [pauldemarco/flutter_blue#558]
Hello community,

when I check the scan results on iOS it just shows me a long id and on android, it shows me the correct mac address.
Is there a way to show the MAC address on iOS?

Thank you in advance,

cheers
Kevin

**Comment by keehoo** [comment]
I'm experiencing the same thing also, the name of the device is different from Android. I would really appreciate someone having a look at this?

`flutter_blue: ^0.7.2`

`child: Text(
                '${device.id.id.toUpperCase()} ${device.name.toUpperCase()}',
                style: TextStyle(color: Colors.white),
              ),`




![IMG_15C31FAB0BCE-1](https://user-images.githubusercontent.com/14889069/81179139-89101900-8fa9-11ea-8f35-6053eaf7466f.jpeg)

**Comment by keehoo** [comment]
Just to add to this request: I found the following snippets https://stackoverflow.com/questions/18973098/get-mac-address-of-bluetooth-low-energy-peripheral

please take a look at jlandyr's answer (answered Aug 29 '19 at 11:11)

Perhaps someone is capable of answering if this is even possible to do?

**Comment by KevinRohn** [comment]
any updates?

**Comment by fyredave** [comment]
This is also causing me issues, in my case I'd like to identify if it's one of our IoT devices using the scanresults but this doesn't seem possible on iOS without checking the characteristics

**Comment by jkano** [comment]
This is a limitation on iOS, not an issue of flutter_blue. This is the way as iOS identifies a device. It computes a unique identifier (uuid) using the device mac but the mac itself is not available when scanning a Bluetooth device.

**Comment by KevinRohn** [comment]
> This is a limitation on iOS, not an issue of flutter_blue. This is the way as iOS identifies a device. It computes a unique identifier (uuid) using the device mac but the mac itself is not available when scanning a Bluetooth device.

Thank you for the answer. I've also checked it in the apple developer forum and I seems to be correct. It seems like it'a an security design to not show the MAC address, because it can also be changed. https://developer.apple.com/forums/thread/105064
