### ISSUE TITLE
ios13  gray screen;

### ISSUE THREAD

**Issue by cander0815** [pauldemarco/flutter_blue#566]
Obtaining permissions when entering the app for the first time on ios13.3.2 will cause the app to get stuck on a gray screen;

**Comment by FaresKis** [comment]
Same problem here : 
`2020-05-05 17:21:33.497289+0200 Runner[22288:6622190] [VERBOSE-2:engine.cc(127)] Engine run configuration was invalid.
2020-05-05 17:21:33.497366+0200 Runner[22288:6622190] [VERBOSE-2:shell.cc(437)] Could not launch engine with configuration.`

At first I had an issue with permissions, so I added them on

**Comment by cander0815** [comment]
> Same problem here :
> `2020-05-05 17:21:33.497289+0200 Runner[22288:6622190] [VERBOSE-2:engine.cc(127)] Engine run configuration was invalid. 2020-05-05 17:21:33.497366+0200 Runner[22288:6622190] [VERBOSE-2:shell.cc(437)] Could not launch engine with configuration.`
> 
> At first I had an issue with permissions, so I added them on

Hello, my problem confirmation is caused by the configuration of multiple languages, it has been fixed, you confirm the cause of your problem, or re-issue a problem
