### ISSUE TITLE
[iOS] scan for devices with service UUIDs

### ISSUE THREAD

**Issue by pauldemarco** [pauldemarco/flutter_blue#64]
iOS allows for scanning by service UUID:
https://developer.apple.com/documentation/corebluetooth/cbcentralmanager/1518986-scanforperipherals

Support needed native side.

**Comment by jack4git** [comment]
Paul, confirming this works for me.

**Comment by pauldemarco** [comment]
Thanks for the report!

**Comment by 0x77dev** [comment]
So how to apply filter?
