### ISSUE TITLE
Turn On / Turn Off Bluetooth

### ISSUE THREAD

**Issue by javiervalero31** [pauldemarco/flutter_blue#647]
I only need know if is possible to turning on and turning off the Bluetooth from the flutter_blue lib.
If it is possible I need some examples to do this issue.

I have searched during several hours but I did not finded anything ! 
Can someone  help me, please?

**Comment by JUREXT** [comment]
Find out the state:
- FlutterBlue.instance.isAvailable
- FlutterBlue.instance.isOn
Then use a package like: https://pub.dev/packages/system_setting and open settings.
Or a popup dialog to inform user to do something with the bluetooth.

**Comment by javiervalero31** [comment]
Thanks.
I hope got it feature in the lib soon. Is the most important and will be friendly if the user could turning on or turning off the Bluetooth from the app and not from the Android Settings Screen.

@JUREXT  Does you know if the options you gave me are supported by iOS ?

**Comment by javiervalero31** [comment]
> Thanks.
> I hope got it feature in the lib soon. Is the most important and will be friendly if the user could turning on or turning off the Bluetooth from the app and not from the Android Settings Screen.
> 
> @JUREXT Does you know if the options you gave me are supported by iOS ?

If it helps someone, i will respond to myself...  Yes, the system_settings is supported to iOS
