### ISSUE TITLE
Do you support the classic bluetooth?

### ISSUE THREAD

**Issue by zlj-zz** [pauldemarco/flutter_blue#661]
The title is my question, the project seem like just support the BLE

**Comment by ln-12** [comment]
As far as I see, the plugin only supports Bluetooth LE for now. The corresponding line for android should be [here](https://github.com/pauldemarco/flutter_blue/blob/207943a21a3d7ffd4a0d39a0518f50bd65ab820d/android/src/main/java/com/pauldemarco/flutter_blue/FlutterBluePlugin.java#L802). It should be no problem to add a parameter to decide which variant to use and I would also be very happ to see it in a future release. 

Is this going to be implemented?
