### ISSUE TITLE
Can I use flutter blue to act as a BLE server?

### ISSUE THREAD

**Issue by Ajorona** [pauldemarco/flutter_blue#666]
From the docs I am not sure if this is supported. I would like to create a server and client stream in order to support a Custom Serial Chat Service:

<img width="623" alt="Screen Shot 2020-09-01 at 3 00 21 PM" src="https://user-images.githubusercontent.com/18336445/91910475-f1bf8780-ec63-11ea-8e9f-6b4b1c7d0dce.png">

This is a custom protocol on the ATSAMB11 board manufactured by MicroChip Technologies.

**Comment by orevial** [comment]
> I'm not sure iOS supports BLE in peripheral mode

Apparently iOS supports BLE in peripheral mode, see [Core Bluetooth Programming Guide](https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/CoreBluetooth_concepts/PerformingCommonPeripheralRoleTasks/PerformingCommonPeripheralRoleTasks.html#//apple_ref/doc/uid/TP40013257-CH4-SW1) for more information

**Comment by Ajorona** [comment]
I believe the answer is no for this plugin.
