### ISSUE TITLE
Protobufs

### ISSUE THREAD

**Issue by gedw99** [pauldemarco/flutter_blue#68]
This is a general question about using platform services with protobuf.

This is one of few flutter libs that is using the Dart Protobuf library and so I would like some advice.

I need to write a service in golang to run as a background service that many GUI foreground flutter apps can use.

Wrapping the golang code with the required Android and iOS code is no biggie. But I presume that I can expose it yo the foreground flutter apps over protobufs just like this lib does ?

I presume rather than using method Channels I should use platform channels ?. This is the Flutter terminology.

I presume that if I wrote 2 flutter foreground apps they will both reference the background service as a plug-in.

Lastly my background " platform service " has its own little database in it and it wakes up ever now and then to call the network server and exchange data. Running background services is a big no no these days on mobiles do I presume the only way is to use the Alarm plugin. ? I think that the Flutter team has not fully resolved how this aspect works on iOS.

Again sorry about the general questions, but I am using protobufs on many projects and it looks like this project is a similar architype / example of the same thing I need to build.

**Comment by pauldemarco** [comment]
Your questions are far reaching into different aspects of the flutter world, but I'll try my best:

> Wrapping the golang code with the required Android and iOS code is no biggie. But I presume that I can expose it yo the foreground flutter apps over protobufs just like this lib does ?

Yes, protobufs allow you to share models with getters/setters across the different platforms. This allows you to take advantage of code generation and decrease mistakes when packaging/unpackaging data.

> I presume rather than using method Channels I should use platform channels ?. This is the Flutter terminology.

MethodChannel is a type of Platform Channel, the other is the [EventChannel](https://docs.flutter.io/flutter/services/EventChannel-class.html) which has a more "stream"-like behavior.

> I presume that if I wrote 2 flutter foreground apps they will both reference the background service as a plug-in.

The Flutter team has made great progress on background execution, tracked in issue: https://github.com/flutter/flutter/issues/3671

You may have better luck asking on StackOverflow, where a proper discussion could take place and be archived.
