### ISSUE TITLE
Data filled in a packet

### ISSUE THREAD

**Issue by eugenelet** [pauldemarco/flutter_blue#69]
Hello,

I'm trying to send a packet consisting of 20 bytes and I noticed that it always follows with a '\n' on the end of the packet. So if I send a 19 bytes packet, it will automatically send a 20 bytes packet with a '\n' at the end. I'm still finding out if it's a software or hardware issue. Any idea? Thanks!

Eugene

**Comment by pauldemarco** [comment]
Hi Eugene,

Can you the code?

**Comment by eugenelet** [comment]
Hi Paul,

I've solved this problem. It's the problem with my receiving end. I've solved this problem and forgot to close the issue. Thanks for helping!
