### ISSUE TITLE
Classic Bluetooth support

### ISSUE THREAD

**Issue by gamelaster** [pauldemarco/flutter_blue#73]
Hello, I have my device which using the classic Bluetooth, communicating via Serial.
It's possible to have support for this in the library?
Thanks

**Comment by ddovidenko** [comment]
definitely interested in this too

**Comment by chapus** [comment]
I'm interested also in classic Bluetooth communication.  There is a ScanMode option in the scan method, but none of the options can view classic Bluetooth.  What we can do to accomplish this, the android libraries are not compatible ?

**Comment by jack4git** [comment]
On iOS at least, the CoreBluetooth framework used by flutter_blue is for Bluetooth Low Energy only.

**Comment by GertJOdendaal** [comment]
Really need this in my current project.

**Comment by martyglaubitz** [comment]
Same here i rely on scanning for non Low Energy Devices as well

**Comment by KhoomeiK** [comment]
Any update on this? I'm unable to test with an HC-05 due to lack of support.

**Comment by brianschardt** [comment]
I need this for my current project as well! Any updates? Anybody know how to program this, I will pay for this to happen.

**Comment by edufolly** [comment]
Hi folks, I tried to find a plugin to do the interface with an HC-05 Bluetooth adapter, but I didn't find. So I started to dev one, based on flutter-blue and I would like to get your opinions and improvements. I'm waiting for your comments. https://github.com/edufolly/flutter_bluetooth_serial

**Comment by ddovidenko** [comment]
Dude way to go! I'm going to check it out today. This is very important for a project I'm working on. I saw another gentleman started working on one, but it didn't seem to get any traction. I'll check this out this week and tell you what I think!

**Comment by pauldemarco** [comment]
Bluetooth Classic/Serial support will be tracked in issue #118
