### ISSUE TITLE
When will NNBD arrive?

### ISSUE THREAD

**Issue by aabounegm** [pauldemarco/flutter_blue#734]
Are there any plans to migrate the package to null-safety soon? All the dependencies now seem to offer null-safe versions

**Comment by shinayser** [comment]
@pauldemarco can you take a look on this, please?

**Comment by savs90** [comment]
Any updates on this one guys ?

**Comment by jlubeck** [comment]
Null safety is now on stable branch since yesterday, so it would be nice to have this so we can convert out projects to fully null safety. Thanks!

**Comment by safield** [comment]
Guys I don't know why no one has put 2+2 together yet, but this library is not actively maintained.

Migrate to one of the following...

https://github.com/PhilipsHue/flutter_reactive_ble
https://github.com/Polidea/FlutterBleLib

**Comment by jlubeck** [comment]
Thank you @safield , made the comment hoping it would get some traction, and you comment gave me traction

**Comment by spiderion** [comment]
flutter_blue:
    git:
      url: https://github.com/spiderion/flutter_blue_null_safety

**Comment by navaronbracke** [comment]
Version 0.8.0 now has Null Safety.
