### ISSUE TITLE
Detect sudden disconnects of device and handle the error

### ISSUE THREAD

**Issue by realrk69** [pauldemarco/flutter_blue#739]
I want to continuously detect the connection of the device, only pausing when running some functions and continuing monitoring afterwards.
So, if the connection abruptly disconnects, handle the error and set status of device to be disconnected -> Redirect to reconnect page etc. Any clue how to implement this?

Also, can someone explain the usage of BLEState object?

**Comment by ayushin** [comment]
device.state stream seems to be what you need?

**Comment by realrk69** [comment]
Ah, thanks a ton, missed that in the API docs!
