### ISSUE TITLE
Simulate blue

### ISSUE THREAD

**Issue by Asoseil** [pauldemarco/flutter_blue#75]
Is there a way to simulate a blue device using the phone?

**Comment by nhardt** [comment]
Tried to find this as well. It looks like it is unsupported by the android emulator.

https://developer.android.com/studio/run/emulator

```
The Android Emulator doesn't include virtual hardware for the following:
   Bluetooth
...
```

**Comment by pauldemarco** [comment]
Closing this, please re-open and elaborate if it's still an issue.
