### ISSUE TITLE
Example App crashes on write to a characteristic

### ISSUE THREAD

**Issue by ssaylanc** [pauldemarco/flutter_blue#79]
Example app in the library crashes when I try to write a value.

**Comment by pauldemarco** [comment]
Can you please share the log of the crash?

**Comment by pauldemarco** [comment]
Going to close this until further information is provided.

**Comment by RyanYANG52** [comment]
I have the same problem, using example app, if I tap the writeCharacteristic too quickly, it'll crash. => `PlatformException(write_characteristic_error, writeCharacteristic failed, null)` in messsage_codecs.dart , decodeEnvlope method.

I also write a test app, after call discoverServices and found the right service, writeCharacteristic  immediately will cause the same error.
```
      _characteristic = _service.characteristics.first;

      _device.setNotifyValue(_characteristic, true);

      _valueChangedSubscription = _device
          .onValueChanged(_characteristic)
          .listen((d) => _handleRxData(d));

     // await Future.delayed(const Duration(milliseconds: 100));

     _device.writeCharacteristic(_characteristic, _writeCmd);
```
Uncomment the Future.delayed line, it works without error

**Comment by aBuder** [comment]
Is any update here?
