### ISSUE TITLE
Flutter blue doesn't work after bundle compilation

### ISSUE THREAD

**Issue by pascalzellner** [pauldemarco/flutter_blue#828]
Hi, I wrote an app that use flutter to detect and record RR data from heart rate sensor; on debug mode, everything work but after compilation on bundle for android (aab file), the installation from google play is OK, but when I launch the APP, the BT is on, GPS is on. Still, APP doesn't détect the BT on... The code is available here : https://github.com/pascalzellner/mismirrmonitor

**Comment by kyle215** [comment]
我遇到的问题和你一样

**Comment by pascalzellner** [comment]
The solution is here https://github.com/pauldemarco/flutter_blue/issues/772#issuecomment-783229078, it's works for me, just modify the Gradle built. I close the issue
