### ISSUE TITLE
Problem After characteristic.setNotifyValue(true);

### ISSUE THREAD

**Issue by yuriboeira11tx** [pauldemarco/flutter_blue#841]
After ```await characteristic.setNotifyValue (true);``` the reading does not bring any data.

**Comment by ahoelzemann** [comment]
sounds weird, but try to set it to false first and then again true. It worked in my case. https://github.com/pauldemarco/flutter_blue/issues/840

**Comment by yuriboeira11tx** [comment]
Really sounds weird, but i'm going try it!

**Comment by yuriboeira11tx** [comment]
WTF, it's works! At least temporarily.

**Comment by ahoelzemann** [comment]
I'm glad i could help you!
