### ISSUE TITLE
Find the same device more than one time in scanning

### ISSUE THREAD

**Issue by meridorkobi** [pauldemarco/flutter_blue#894]
I'm using flutter_blue to to scan for devices.
The device could open and close more than one time while app working.
I can find the the devices only in first time.
Is it a way to enable duplicates?

This is the code inside initState()
  flutterBlueInstance.scan().listen((event) {
  if (event.device.name == "XXXXX") {
      final DateTime now = DateTime.now();
      loggerDBNDI("found [$now] -");
    }});

**Comment by dhaval2017** [comment]
FlutterBlue.instance.scan(allowDuplicates: true);

**Comment by meridorkobi** [comment]
Thanks
