### ISSUE TITLE
Write characteristic more than 20 bytes

### ISSUE THREAD

**Issue by HninNweAye** [pauldemarco/flutter_blue#937]
Currently I can send only 20 bytes. I send more than 20 bytes then it will truncate all the data after 20 bytes.
I need to send large size of data. Is any one have this problem?

**Comment by peekpt** [comment]
If you request MTU change you can send large chunks of data. But you can also split your data

**Comment by HninNweAye** [comment]
I found someone mentioned this answer. It did solved my problem.

await bleReaderDevice?.requestMtu(250);

    final mtuChanged = Completer<void>();
    final mtuStreamSubscription = bleReaderDevice?.mtu.listen((mtu) {
      if (mtu == 250) mtuChanged.complete();
    });
    await mtuChanged.future.timeout(const Duration(seconds: 2)).catchError(
        (dynamic error) =>
            debugPrint(error.toString())); // set timeout and catch exception
    mtuStreamSubscription?.cancel();

**Comment by Enemias-Itzep** [comment]
@HninNweAye Where did you make this change?
