### ISSUE TITLE
Can not run my application 

### ISSUE THREAD

**Issue by fedorstepanovv** [pauldemarco/flutter_blue#938]
Before I had been using  flutter_blue: 0.8.0 for a while, but then i couldnt run my app because of the issue below:
* What went wrong:
Execution failed for task ':flutter_blue:generateDebugProto'.
> Could not resolve all files for configuration ':flutter_blue:protobufToolsLocator_protoc'.
   > Could not find protoc-3.11.4-osx-aarch_64.exe (com.google.protobuf:protoc:3.11.4).
     Searched in the following locations:
         https://jcenter.bintray.com/com/google/protobuf/protoc/3.11.4/protoc-3.11.4-osx-aarch_64.exe

It seems like there are some sort of problems with jcenter, because the url right from the error doesnt work.

**Comment by sanatChoubey** [comment]
@fedorstepanovv  have you got a solution?

**Comment by fedorstepanovv** [comment]
No, I don’t. But on my intel mac it works perfectly fine. 

> @fedorstepanovv have you got a solution?
> I have change jcenter to maven but still getting the same issue
> <img alt="Screenshot 2021-09-16 at 5 25 01 PM" width="921" src="https://user-images.githubusercontent.com/42996051/133613393-6e9f13db-e676-421e-82ca-94ed7c1555c1.png">

**Comment by peekpt** [comment]
https://github.com/pauldemarco/flutter_blue/pull/899

**Comment by fedorstepanovv** [comment]
> #899

@peekpt , where exactly do i need to paste this line? As i unterstood this part of code must be in android/build.gradle. But it doesnt seem like a line that was written in the reply right for build.gradle

**Comment by peekpt** [comment]
Fork code and apply PullReq to your fork. Or use the authors fork/branch that includes the PR in pubspec

**Comment by sanatChoubey** [comment]
@fedorstepanovv  I found a solution
<img width="761" alt="Screenshot 2021-09-17 at 12 46 28 PM" src="https://user-images.githubusercontent.com/42996051/133741846-d2ed78bb-99ea-45ad-9bcd-c836beeaa6a2.png">
<img width="1367" alt="Screenshot 2021-09-17 at 12 47 22 PM" src="https://user-images.githubusercontent.com/42996051/133741911-b221a782-87b1-4406-b403-b0bd119b1f38.png">

first go to your-> flutter project/android/build.gradle
and add ext.protoc_platform = osx-x86_64
and then open android folder in android studio
and in side bar you will find flutter blue and in flutter blue open build.gradle and add second image code.

**Comment by fedorstepanovv** [comment]
The issue was solved, i tried to add lines, which @sanatChoubey has shared, but in my case i opened android project folder in android studio and synchronized my build.gradle file. It took around 14 mins  to install everything. So, after that step, my app launches without any addional lines.
