### ISSUE TITLE
Fork List (with enhancements and PR)

### ISSUE THREAD

**Issue by peekpt** [pauldemarco/flutter_blue#951]
Since this plugin's development is on hold, please post here what are the Fork you are using and reason.

 -- fork:
 
 -- reason?:

**Comment by peekpt** [comment]
fork: https://github.com/MZachmann/flutter_blue

reason: It has updated to last PR, can control Bluetooth and can read RSSI from peripheral

**Comment by boskokg** [comment]
please read this: https://github.com/pauldemarco/flutter_blue/issues/929#issuecomment-927268881

**Comment by boskokg** [comment]
@peekpt can you please close this issue?

**Comment by peekpt** [comment]
@boskokg I reopen the issue because I found  MZachmann's fork differences:
 - mtuRequest returns the MTU 
 - turnOn and turnOff Bluetooth on Android

**Comment by boskokg** [comment]
I will add them today. Please continue writing there, not here so others can catch the entire discussion in one place.

**Comment by peekpt** [comment]
@boskokg  Ok thank you for your job. I will close this
