### ISSUE TITLE
Question: Next release date?

### ISSUE THREAD

**Issue by dangabdolfo** [pauldemarco/flutter_blue#955]
Hi every one,

Have you an idea about the next release date?

I can see that several bugs are pending in the pull request. When do you think merge it?

Regards,
Daniel

**Comment by ViliusP** [comment]
Use https://github.com/boskokg/flutter_blue/ fork for now. It has most of pull requests merged. All changes are written in https://github.com/pauldemarco/flutter_blue/issues/929

**Comment by dangabdolfo** [comment]
Thanks for this information. I will try it now.

Regards,
Daniel
