### ISSUE TITLE
Updating dependencies broke iOS support

### ISSUE THREAD

**Issue by LeoBound** [pauldemarco/flutter_blue#985]
Hi,

I ran flutter pub upgrade --major-versions earlier today and since then I have been unable to connect to any devices on iOS with the following error:

[CoreBluetooth] API MISUSE: Cancelling connection for unused peripheral <CBPeripheral: 0x283ca4c60, identifier = 48752E91-E2D6-3E4F-03B7-76973E5C1910, name = testDevice, mtu = 0, state = connecting>, Did you forget to keep a reference to it?

Any ideas, Android still works fine.

Thanks.

**Comment by LeoBound** [comment]
It turns out this was due to me doing a setState while connecting, although I'm unsure why this only is a problem on iOS

**Comment by alexvnesta** [comment]
same error here - had this issue because I called setState while scanning for devices.
