### ISSUE TITLE
BLE didn`t work in release version android

### ISSUE THREAD

**Issue by TeslaWorks239** [pauldemarco/flutter_blue#986]
BLE do nothing in release but in debug version everything fine. I use 0.8.0 version of Flutter blue. All permission I added. I checked all methods from other issues but nothing helped

build.gradle file: 

  buildTypes {
        release {
            signingConfig signingConfigs.debug
            shrinkResources false
            minifyEnabled false
        }
    }

During build apk I get this message

Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_blue-0.8.0\android\src\main\java\com\pauldemarco\flutter_blue\FlutterBluePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by qinjinze** [comment]
The Bluetooth status can be obtained by debugging and installing on the real machine, but the Bluetooth status cannot be obtained after compiling the apk

**Comment by peekpt** [comment]
You need to setup the proguard rules, search the issues there's something about it

**Comment by TeslaWorks239** [comment]
Thank you! I add this and everything work fine
![image](https://user-images.githubusercontent.com/57033593/143779816-4db8d853-408d-4890-9a98-15a555610123.png)

**Comment by FarhanRiaaz** [comment]
Why don't you put 
`signingConfig signingConfigs.release`

instead of this
`signingConfig signingConfigs.debug`

**Comment by littleantsos** [comment]
> Thank you! I add this and everything work fine ![image](https://user-images.githubusercontent.com/57033593/143779816-4db8d853-408d-4890-9a98-15a555610123.png)
It worked

**Comment by FredyKonig** [comment]
Do we also have a fix for the IOS build?

**Comment by boskokg** [comment]
use flutter_blue_plus

**Comment by FredyKonig** [comment]
> use flutter_blue_plus

Thanks, we tried using flutter_blue_plus but it doesn't seem to have fixed it in the IOS release version.
