### ISSUE TITLE
How to Get/receive data from Bluetooth device?

### ISSUE THREAD

**Issue by Logamuhilan** [pauldemarco/flutter_blue#996]
I am using flutter_blue to connect and get Bluetooth device data, my problem is i don't know **the method to get data** from it. I have used "await c.read" it gives only device name, and "await d.read" it gives only empty array. here "c" and "d" is characteristics. I think read is not a method. Is there any method to get data from my device? Cheers in advance ; )

**Comment by oooldCaption** [comment]
like this : 
```
//  characteristic --> your's notification characteristic
await characteristic.setNotifyValue(true);
characteristic.value.listen((value) {
// this   value   are the data uploaded by the Bluetooth device 
    // do something with new value
});
```

**Comment by Logamuhilan** [comment]
> like this : 
> ```
> //  characteristic --> your's notification characteristic
> await characteristic.setNotifyValue(true);
> characteristic.value.listen((value) {
> // this   value   are the data uploaded by the Bluetooth device 
>     // do something with new value
> });
> ```

Thanks for your response 👍🏼

**Comment by dinhvuvan1996** [comment]
Hi @Logamuhilan, the same problem is occurring to me. I tried to use @oooldCaption 's solution but it not work, I can't pass the line: await characteristic.setNotifyValue(true);. Please help me

**Comment by oooldCaption** [comment]
code like this: 
do u add `async ` on you function ?

  getNotify() async{
    await characteristic.setNotifyValue(true);
    characteristic.value.listen((value) {
// this   value   are the data uploaded by the Bluetooth device 
      // do something with new value
    });
  }
